### ISSUE TITLE
Custom Scaling

### ISSUE THREAD

**Issue by jackyyang09** [dabeschte/VRArmIK#1]
Hi, thanks for developing this plugin!

I want to use it for a VR game where the player's camera rig will be scaled up. As a result the avatar and shoulder objects will have to be scaled to match, however this causes a lot of things to go wrong. Would it be possible to make your solution work at a scale of say, 15x on all axes?

Thanks in advance

**Comment by dabeschte** [comment]
Hi!
Sorry for the late response, i accidently disabled all E-Mail notifications and did not see this message.

yes, this should totally work. You can just scale up the avatar 15x too on all axes, but then you also have to set a 15x higher "playerHeightHmd" in the PoseManager.

But I guess at this moment you might have found your own solution already.
