### ISSUE TITLE
Oculus Hands

### ISSUE THREAD

**Issue by CequixJoe** [dabeschte/VRArmIK#2]
Hello,

I love this plugin, and am trying to use it to build a VR game for Oculus Rift/Quest. I would like to use the Oculus hand prefabs with this plugin, but I don't know how to set them up without breaking it. It almost works right if I child the hand prefabs to the Hand transform in your supplied arm prefab, but when the editor runs the hands usually generate way out of place with no way to bring them back closer. Do you have any idea why that might be or have any experience working with the Oculus samples?

Thanks,
Joe

**Comment by dabeschte** [comment]
Hi! Sorry for taking so long.
I don't know if this is still helpful to you, but I still want to answer you question.

Unfortunately I do not have experience with Oculus samples, but I think I know the issue.
If you only attach a mesh to the hands, you should not have any issues with that besides maybe a offset position or rotation that you need to fine tune. But if you are using the Oculus hand prefab, i guess that there is a script attached to the prefab that updates the position relative to the hand of VRArmIK. So either disable that script or use the Oculus hand prefab as root gameobject (not as child of VRArmIK hands).
