### ISSUE TITLE
Avatar Facing Down

### ISSUE THREAD

**Issue by 12DrewMileham13** [dabeschte/VRArmIK#3]
I know this problem was in the readme, but it was just explained so poorly. My problem is that the avatar is facing downwards which screws up the entire system. I need a better explanation on how to fix this. Thanks.

**Comment by dabeschte** [comment]
Hi! Sorry for taking so long. I do not remember all steps on how to solve that issue, but if you are using an Oculus HMD, you should have a good pose estimation. Unfortunately, I am on vacation for a weeks now and won't be able to look into that for now. 
If you find a more detailed solution, please let us know.
You should only have to look into PoseManager and ShoulderPoser for that

**Comment by 12DrewMileham13** [comment]
Thanks for getting back to me! I did actually figure out a solution. You
have to go into the pose manager script and in the start function simply
write "playerHeightHmd = -1.7f;". That totally fixes the problem.

**Comment by dabeschte** [comment]
Ok good to know, thank you! 
I need to try that myself. Maybe I can somehow integrate this fix into the scripts if I detect other headsets.

**Comment by 12DrewMileham13** [comment]
No problem, I recommend changing the .readme where it states the problem
and answer. I and some others were having trouble understanding. Nice talk,
and great asset. Keep at it :)

**Comment by dabeschte** [comment]
Hi!
I tried to fix this issue in the branch _platform-fixes_.
Since I do not have the hardware to check if this fix works, could you maybe try if that branch fixes your issues?

**Comment by 12DrewMileham13** [comment]
Of couse! Sorry for the late reply, I didnt get the notification until now.
My PC is currently getting checked out so it might be a day or two till i
get it fixed. Ill let you know.

**Comment by 12DrewMileham13** [comment]
The fix is working great. Good job on the asset!

**Comment by dabeschte** [comment]
Great! Thanks a lot for helping me out and confirming that. I really appreciate it!
