### ISSUE TITLE
Full body avatar rotations won't rotate shoulders

### ISSUE THREAD

**Issue by jasonofthestorm** [dabeschte/VRArmIK#5]
Hi and thanks for the awesome asset! In my project I have the player set as the child of a moving object, specifically the cockpit of a ship. The ship is able to move and rotate freely, and the player follows its position perfectly, but when the ship rotates on the X and Z axes, the Shoulder object under the Avatar does not follow and instead remains vertically oriented in the world (so when the ship is upside down, the player's body now appears to be above their head). My desired behavior is for the entire avatar to stay locked to the ship's orientation (so if the player remains perfectly still while the ship does a flip, the avatar should remain perfectly fixed in place relative to the player's perspective). I've managed to get as far as locking the Shoulder's local X and Z rotations to the ship's orientation, but then the Shoulder will still rotate on it's local Y axis unexpectedly during flips. Do you have any tips or ideas on how this could be solved?

**Comment by jasonofthestorm** [comment]
Managed to get it working through trial and error by modifying rotations and positions to their local orientations in the ShoulderPoser script. It's pretty hacky but I put up a fork with the modified script if anyone else would like to use it!

[https://github.com/jasonofthestorm/VRArmIK](https://github.com/jasonofthestorm/VRArmIK)

**Comment by dabeschte** [comment]
Sorry for taking so long.
Yes, VRArmIK is always looking upwards in world space. Your solution seems to work. But in case it does not, a pretty easy hack would be to have the VRArmIK avatar somewhere hidden in world space and just copy the local rotations over to your player avatar.

And thanks for sharing the solution!
