### ISSUE TITLE
SteamVR glove hand replacement not behaving as desired

### ISSUE THREAD

**Issue by LMBooth** [dabeschte/VRArmIK#8]
Hey, i'm having a similar issue with the SteamVR_Input as issue #2, i've replaced the original hand with the Steam_VR vr_glove prefab, attached a mesh collider to my vr_glove and now skeleton poses are working with the VRarmIK, my only issue is the glove is now deformed and at the wrong angle, do you have any recommendations to fix this? (I know the repository is not regularly supported but this may help someone in the future)

**Comment by dabeschte** [comment]
Hi! I have not used the Steam_VR gloves before, so I am not sure how to solve it. But I have a few recommendations: did you remove all scripts from the gloves prefab if there are any? Could be that they have some animation scripts on them. Did you also make sure that the gloves have the same orientation as the defaults hands? (the palms should touch each other)

And the deformation sounds like either the gloves have additional scripts on them or they are not children of the VRArmIK hands

**Comment by LMBooth** [comment]
Sorry for the late response, and thank you for your hasty one. 

You are right on both accounts, my scripts animating the gloves were still attached which was transforming the position and i hadn't made them children to the VRArmIK hands. They are now moving as desired, i've still lost the animation from the gloves but i'm planning to look at animating the gloves myself instead of using the stock ones over the next few days. So i'll close for now, i'm also looking at implementing this proeject with the new Unity XR interface, as discussed in #7, if i make some good progress i'll make sure to post a link to a cloned repository or offer a merge down the line.

Thanks again
